services:
  bot:
    build: .
    restart: always
    depends_on:
      - pgdb
    secrets:
      - webhook_secret
      - bot_token
      - openai_token
      - db_password
    env_file:
      - .env
    ports:
      - "8080:8080" 
      - "5678:5678" # for debugger

  webserver:
    image: jonasal/nginx-certbot:5.2.0 # nginx with automatic SSL certificate issuance
    restart: always
    depends_on:
      - bot
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl_cert:/etc/letsencrypt # storage for issued SSL certificate
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template # nginx config

  pgdb:
    image: postgres:latest
    shm_size: 128mb
    restart: always
    secrets:
      - db_password
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # database data
      - ./pgdb_scheme.sql:/docker-entrypoint-initdb.d/scheme.sql # initialization files

volumes:
  ssl_cert:
  pgdata:


secrets:
  webhook_secret:
    file: ./secrets/webhook_secret.txt
  bot_token:
    file: ./secrets/bot_token.txt
  openai_token:
    file: ./secrets/openai_token.txt
  db_password:
    file: ./secrets/db_password.txt
